In [4]:
import pandas as pd

In [5]:
#Q2
dm=pd.read_csv('diamonds.csv')

In [6]:
dm.carat

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ...
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [7]:
#Q3
dm.rename(columns={'x':'Length','y':'Width'})

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,Length,Width,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [8]:
cut=dm.cut

In [9]:
cut.sort_values

<bound method Series.sort_values of 0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: object>

In [10]:
dm1=pd.read_csv('diamonds.csv')

In [11]:
d=dm1[(dm1['cut']=='Good') | (dm1['cut']=='Premium') | (dm1['cut']=='Fair')]

In [12]:
d

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
...,...,...,...,...,...,...,...,...,...,...,...
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74

In [15]:
dm1[dm1['price'] == max(dm1['price'])]['carat']

27749    2.29
Name: carat, dtype: float64

In [16]:
dm1[dm1['price'] == min(dm1['price'])]['carat']

0    0.23
1    0.21
Name: carat, dtype: float64

In [17]:
dm1.info

<bound method DataFrame.info of        Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34
...           ...    ...        ...   ...     ...    ...    ...    ...   ...
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83

          y     z
0      3.98  2.43
1      3.84  2.31
2      4.07  2.31
3      4.23  2.63
4      4.35  2.75
...     ...   ...
53935  5.76  3.50
53936  5.75  3.61
53937  5.68  3.56
53938  6.12  3.74
53939  5.87  3.64

[53940 rows x 11 columns]>